# endcoding 

 * encoding means converting the data from one format into onother format is known as encoding 
 * why need this because ml don't read the string they only know the numbers like 0 or 1
 * types of encoding:-
 * 1. label encoding
 * 2. one hot encodign
 * 3. Ordinal Encoding (Used when the categories have a natural order.) like :-
 * | Education   | Encoded |
| ----------- | ------- |
| High School | 1       |
| Bachelor’s  | 2       |
| Master’s    | 3       |
| PhD         | 4       |

* 4️⃣ Frequency / Count Encoding (Replace each category with how often it appears.)
| City   | Frequency |
| ------ | --------- |
| Delhi  | 3         |
| Mumbai | 2         |
| Delhi  | 3         |
| Pune   | 1         |

* 5️⃣ Binary / Hash / Target Encoding (Used for large datasets or high-cardinality features (e.g., 1000+ categories).)

   # this is summary tabel
* | Encoding Type         | Best for             | Description                          |
| --------------------- | -------------------- | ------------------------------------ |
| **Label Encoding**    | Simple categories    | Assigns numeric labels (0, 1, 2, …)  |
| **One-Hot Encoding**  | Unordered categories | Creates binary columns               |
| **Ordinal Encoding**  | Ordered categories   | Keeps natural rank (low → high)      |
| **Count / Frequency** | Large categories     | Uses counts of occurrences           |
| **Target Encoding**   | Advanced ML          | Uses relationship to target variable |

*

# ordinary encoding

In [ ]:
import seaborn as sns 
from sklearn.model_selection import train_test_split
print(sns.get_dataset_names())
dataset = sns.load_dataset('tips')
dataset

In [46]:
print(dataset['day'].value_counts())
print(dataset['time'].value_counts())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [28]:
x = dataset.iloc[:,0:-1]
y = dataset.iloc[:,-1]

In [64]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [65]:
x_train

     total_bill   tip     sex smoker   day    time
99        12.46  1.50    Male     No   Fri  Dinner
25        17.81  2.34    Male     No   Sat  Dinner
211       25.89  5.16    Male    Yes   Sat  Dinner
148        9.78  1.73    Male     No  Thur   Lunch
136       10.33  2.00  Female     No  Thur   Lunch
..          ...   ...     ...    ...   ...     ...
187       30.46  2.00    Male    Yes   Sun  Dinner
166       20.76  2.24    Male     No   Sun  Dinner
47        32.40  6.00    Male     No   Sun  Dinner
63        18.29  3.76    Male    Yes   Sat  Dinner
88        24.71  5.85    Male     No  Thur   Lunch

[195 rows x 6 columns]

In [135]:
from sklearn.preprocessing import OrdinalEncoder
col = ['day','time']
oe = OrdinalEncoder(categories = [['Thur','Fri','Sat','Sun'],['Lunch','Dinner']]) 
# categories parameter is used for arrange the order as you wish
oe.fit_transform(x_train[col])

array([[1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [1., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [3., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [1., 0.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [1., 1.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [1., 0.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [1., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [0., 0.]])

In [74]:
# some attributes 
oe.categories_ # shoing the categories name

[array(['Thur', 'Fri', 'Sat', 'Sun'], dtype=object),
 array(['Lunch', 'Dinner'], dtype=object)]

# label Encoding

In [1]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

li = ['Red','Blue','Green','Red']
encoding = le.fit_transform(li)
print(encoding)
print(li)

[2 0 1 2]
['Red', 'Blue', 'Green', 'Red']

In [5]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd 
ds = pd.DataFrame({
           'name': ['yash','rani didi','tanisha','suraj','roshni'],
            'gender': ['M','F','F','M','F'],
          'passed': ['yes','yes','no','yes','no']
})
le = LabelEncoder()
ds_label = ds.copy()

ds_label['Gender_endcoded'] = le.fit_transform(ds_label['gender'])
ds_label['Passed_endcoded'] = le.fit_transform(ds_label['passed'])
print(ds_label)

             name gender passed  Gender_endcoded  Passed_endcoded
0            yash      M    yes                1                1
1            rani      F    yes                0                1
2  rani kamlapati      F     no                0                0
3           suraj      M    yes                1                1
4          roshni      F     no                0                0

# one hot coding
use the encoding there are two ways to execute 
 * pd.get_dummies() is a pandas function used to perform One-Hot Encoding automatically.
 * from sklearn.preprocessing import OneHotEncoder

In [3]:
import seaborn as sns
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
print(df['embarked'].value_counts())
print(df['sex'].value_counts())

embarked
S    644
C    168
Q     77
Name: count, dtype: int64
sex
male      577
female    314
Name: count, dtype: int64

In [96]:
pd.get_dummies(df,columns=['embarked','sex'])

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S,sex_female,sex_male
0,0,3,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,False,False,True,False,True
1,1,1,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,True,False,False,True,False
2,1,3,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,False,False,True,True,False
3,1,1,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False,False,False,True,True,False
4,0,3,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,Second,man,True,NaN,Southampton,no,True,False,False,True,False,True
887,1,1,19.0,0,0,30.0000,First,woman,False,B,Southampton,yes,True,False,False,True,True,False
888,0,3,NaN,1,2,23.4500,Third,woman,False,NaN,Southampton,no,False,False,False,True,True,False
889,1,1,26.0,0,0,30.0000,First,man,True,C,Cherbourg,yes,True,True,False,False,False,True
890,0,3,32.0,0,0,7.7500,Third,man,True,NaN,Queenstown,no,True,False,True,False,False,True

# drop_first=True drop the first columns of each coloumns

In [98]:
# n-1 encoding 
pd.get_dummies(df,columns=['embarked','sex'],drop_first=True)

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,embarked_Q,embarked_S,sex_male
0,0,3,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,False,True,True
1,1,1,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,False,False,False
2,1,3,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,False,True,False
3,1,1,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False,False,True,False
4,0,3,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,Second,man,True,NaN,Southampton,no,True,False,True,True
887,1,1,19.0,0,0,30.0000,First,woman,False,B,Southampton,yes,True,False,True,False
888,0,3,NaN,1,2,23.4500,Third,woman,False,NaN,Southampton,no,False,False,True,False
889,1,1,26.0,0,0,30.0000,First,man,True,C,Cherbourg,yes,True,False,False,True
890,0,3,32.0,0,0,7.7500,Third,man,True,NaN,Queenstown,no,True,True,False,True

In [116]:
df.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [5]:
features = df.iloc[:,:-1]
target = df.iloc[:,-1]

In [14]:
from sklearn.model_selection import train_test_split
train_x,test_x,y_train,y_test = train_test_split(features,target,test_size = 0.2)
train_x.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
801,1,2,female,31.0,1,1,26.2500,S,Second,woman,False,NaN,Southampton,yes
522,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no
541,0,3,female,9.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes
663,0,3,male,36.0,0,0,7.4958,S,Third,man,True,NaN,Southampton,no

In [61]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first') # drop='first' remove the first category columns for each no of columns
# sparse_output one more paramenter used for showing the array not use the toarray() fuciton
new_x_train = ohe.fit_transform(train_x[['embarked','sex']]).toarray()
# ohe is creating by defulat sparse matrix 
# toarray() this mehod showing the array
print(new_x_train)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 1.]
 [0. 1. 0.]]

In [49]:
print(new_x_train.shape)

(712, 5)

In [47]:
# putting the remaing features in this encoded data 
import numpy as np 
np.hstack((train_x[['survived','pclass','age']].values,new_x_train)) 
# this hstack fucion is add tow array h and v np.hstack(array1,array2)

array([[ 1.,  2., 31., ...,  1.,  1.,  0.],
       [ 0.,  3., nan, ...,  0.,  0.,  1.],
       [ 0.,  3.,  9., ...,  1.,  1.,  0.],
       ...,
       [ 1.,  3., nan, ...,  0.,  1.,  0.],
       [ 0.,  2., 23., ...,  1.,  0.,  1.],
       [ 1.,  1., 51., ...,  1.,  1.,  0.]], shape=(712, 8))

In [53]:
print(new_x_train.shape)

(712, 3)

In [62]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [73]:
print(df[''].value_counts())
df['deck'].nunique()

alone
True     537
False    354
Name: count, dtype: int64

7

In [7]:
# one hot coding
import pandas as pd 
df = pd.DataFrame({
                'colours':  ['Red','Blue','Green','Red']
})
encodeing = pd.get_dummies(df,columns=['colours'] )  #,dtype=int
print(encodeing)

   colours_Blue  colours_Green  colours_Red
0         False          False         True
1          True          False        False
2         False           True        False
3         False          False         True

# practice for encoding

In [3]:
import seaborn as sns 
ds = sns.load_dataset('flights')
ds

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [150]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# print(this is alll text )
ds['month'] = le.fit_transform(ds['month'])
print(ds['month'].value_counts().sum())
ds

144

     year  month  passengers
0    1949      4         112
1    1949      3         118
2    1949      7         132
3    1949      0         129
4    1949      8         121
..    ...    ...         ...
139  1960      1         606
140  1960     11         508
141  1960     10         461
142  1960      9         390
143  1960      2         432

[144 rows x 3 columns]

In [7]:
import pandas as pd
encoding = pd.get_dummies(ds['year'])