In [1]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import MinMaxScaler,StandardScaler,RobustScaler

In [3]:
df = pd.DataFrame({
    'age':[18,22,30,45,60,80],
    'salary':[20000,25000,40000,60000,120000,1000000]
})
print(df)

   age   salary
0   18    20000
1   22    25000
2   30    40000
3   45    60000
4   60   120000
5   80  1000000

In [26]:
mms = MinMaxScaler()
df_minmax = pd.DataFrame(mms.fit_transform(df) , columns=df.columns)
print(df_minmax)

        age    salary
0  0.000000  0.000000
1  0.064516  0.005102
2  0.193548  0.020408
3  0.435484  0.040816
4  0.677419  0.102041
5  1.000000  1.000000

# Standard scaler

In [28]:
standard_scaler = StandardScaler()
ss_result = pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)
print("\n standard scaled data :- ")
ss_result

 standard scaled data :-

        age    salary
0 -1.115270 -0.538353
1 -0.933185 -0.524248
2 -0.569015 -0.481932
3  0.113803 -0.425510
4  0.796621 -0.256247
5  1.707046  2.226289

# robust scaler

In [35]:
robust_scaler = RobustScaler()
rs_result= pd.DataFrame(robust_scaler.fit_transform(df),columns=df.columns)
rs_result

        age     salary
0 -0.604651  -0.393443
1 -0.480620  -0.327869
2 -0.232558  -0.131148
3  0.232558   0.131148
4  0.697674   0.918033
5  1.317829  12.459016