# Column Transformer

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
ds = sns.load_dataset('flights')
ds

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [13]:
ds['month'].value_counts()

month
Jan    12
Feb    12
Mar    12
Apr    12
May    12
Jun    12
Jul    12
Aug    12
Sep    12
Oct    12
Nov    12
Dec    12
Name: count, dtype: int64

In [10]:
x = ds.iloc[:,:-1]
y = ds.iloc[:,-1]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [21]:
print(x_train.shape)
x_train

(115, 2)

     year month
124  1959   May
31   1951   Aug
98   1957   Mar
36   1952   Jan
16   1950   May
..    ...   ...
71   1954   Dec
106  1957   Nov
14   1950   Mar
92   1956   Sep
102  1957   Jul

[115 rows x 2 columns]

In [12]:
ds.isnull().sum()

year          0
month         0
passengers    0
dtype: int64

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder 
transformer = ColumnTransformer(transformers = [
('t1',OrdinalEncoder(categories = [['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']]),['month'])
],remainder = 'passthrough')

In [24]:
print(transformer.fit_transform(x_train).shape)
transformer.fit_transform(x_train)

(115, 2)

array([[4.000e+00, 1.959e+03],
       [7.000e+00, 1.951e+03],
       [2.000e+00, 1.957e+03],
       [0.000e+00, 1.952e+03],
       [4.000e+00, 1.950e+03],
       [1.000e+01, 1.949e+03],
       [9.000e+00, 1.956e+03],
       [3.000e+00, 1.958e+03],
       [6.000e+00, 1.952e+03],
       [1.000e+01, 1.958e+03],
       [7.000e+00, 1.959e+03],
       [0.000e+00, 1.957e+03],
       [0.000e+00, 1.954e+03],
       [0.000e+00, 1.949e+03],
       [0.000e+00, 1.956e+03],
       [4.000e+00, 1.951e+03],
       [4.000e+00, 1.952e+03],
       [2.000e+00, 1.956e+03],
       [0.000e+00, 1.951e+03],
       [1.000e+00, 1.951e+03],
       [1.100e+01, 1.950e+03],
       [7.000e+00, 1.958e+03],
       [7.000e+00, 1.954e+03],
       [8.000e+00, 1.952e+03],
       [3.000e+00, 1.950e+03],
       [1.100e+01, 1.956e+03],
       [3.000e+00, 1.952e+03],
       [1.000e+01, 1.950e+03],
       [8.000e+00, 1.954e+03],
       [8.000e+00, 1.955e+03],
       [8.000e+00, 1.960e+03],
       [1.100e+01, 1.952e+03],
       [6.000e+00, 1.951e+03],
       [4.000e+00, 1.958e+03],
       [4.000e+00, 1.955e+03],
       [5.000e+00, 1.960e+03],
       [9.000e+00, 1.951e+03],
       [9.000e+00, 1.955e+03],
       [1.000e+01, 1.960e+03],
       [2.000e+00, 1.954e+03],
       [7.000e+00, 1.960e+03],
       [3.000e+00, 1.960e+03],
       [5.000e+00, 1.953e+03],
       [5.000e+00, 1.949e+03],
       [1.000e+00, 1.956e+03],
       [1.000e+00, 1.958e+03],
       [1.000e+00, 1.953e+03],
       [1.100e+01, 1.951e+03],
       [5.000e+00, 1.955e+03],
       [1.000e+01, 1.951e+03],
       [1.100e+01, 1.959e+03],
       [7.000e+00, 1.949e+03],
       [7.000e+00, 1.952e+03],
       [1.000e+01, 1.954e+03],
       [5.000e+00, 1.956e+03],
       [1.100e+01, 1.955e+03],
       [3.000e+00, 1.959e+03],
       [9.000e+00, 1.959e+03],
       [8.000e+00, 1.949e+03],
       [1.000e+00, 1.950e+03],
       [0.000e+00, 1.958e+03],
       [6.000e+00, 1.958e+03],
       [3.000e+00, 1.949e+03],
       [5.000e+00, 1.950e+03],
       [2.000e+00, 1.952e+03],
       [0.000e+00, 1.955e+03],
       [0.000e+00, 1.959e+03],
       [6.000e+00, 1.949e+03],
       [5.000e+00, 1.957e+03],
       [2.000e+00, 1.949e+03],
       [2.000e+00, 1.959e+03],
       [6.000e+00, 1.953e+03],
       [2.000e+00, 1.953e+03],
       [8.000e+00, 1.957e+03],
       [1.000e+01, 1.952e+03],
       [9.000e+00, 1.957e+03],
       [1.000e+00, 1.954e+03],
       [9.000e+00, 1.960e+03],
       [7.000e+00, 1.955e+03],
       [4.000e+00, 1.960e+03],
       [7.000e+00, 1.956e+03],
       [5.000e+00, 1.952e+03],
       [1.000e+01, 1.953e+03],
       [6.000e+00, 1.956e+03],
       [0.000e+00, 1.953e+03],
       [4.000e+00, 1.956e+03],
       [6.000e+00, 1.959e+03],
       [9.000e+00, 1.950e+03],
       [9.000e+00, 1.953e+03],
       [3.000e+00, 1.955e+03],
       [8.000e+00, 1.951e+03],
       [6.000e+00, 1.960e+03],
       [1.100e+01, 1.953e+03],
       [3.000e+00, 1.954e+03],
       [8.000e+00, 1.959e+03],
       [1.000e+00, 1.952e+03],
       [5.000e+00, 1.951e+03],
       [1.100e+01, 1.957e+03],
       [2.000e+00, 1.960e+03],
       [1.000e+00, 1.949e+03],
       [4.000e+00, 1.953e+03],
       [1.000e+01, 1.959e+03],
       [7.000e+00, 1.957e+03],
       [3.000e+00, 1.957e+03],
       [8.000e+00, 1.958e+03],
       [3.000e+00, 1.956e+03],
       [2.000e+00, 1.955e+03],
       [1.000e+00, 1.959e+03],
       [1.100e+01, 1.960e+03],
       [8.000e+00, 1.950e+03],
       [1.100e+01, 1.954e+03],
       [1.000e+01, 1.957e+03],
       [2.000e+00, 1.950e+03],
       [8.000e+00, 1.956e+03],
       [6.000e+00, 1.957e+03]])