# endcoding 

 * encoding means converting the data from one format into onother format is known as encoding 
 * why need this because ml don't read the string they only know the numbers like 0 or 1
 * types of encoding:-
 * 1. label encoding
 * 2. one hot encodign
 * 3. Ordinal Encoding (Used when the categories have a natural order.) like :-
 * | Education   | Encoded |
| ----------- | ------- |
| High School | 1       |
| Bachelor’s  | 2       |
| Master’s    | 3       |
| PhD         | 4       |

* 4️⃣ Frequency / Count Encoding (Replace each category with how often it appears.)
| City   | Frequency |
| ------ | --------- |
| Delhi  | 3         |
| Mumbai | 2         |
| Delhi  | 3         |
| Pune   | 1         |

* 5️⃣ Binary / Hash / Target Encoding (Used for large datasets or high-cardinality features (e.g., 1000+ categories).)

   # this is summary tabel
* | Encoding Type         | Best for             | Description                          |
| --------------------- | -------------------- | ------------------------------------ |
| **Label Encoding**    | Simple categories    | Assigns numeric labels (0, 1, 2, …)  |
| **One-Hot Encoding**  | Unordered categories | Creates binary columns               |
| **Ordinal Encoding**  | Ordered categories   | Keeps natural rank (low → high)      |
| **Count / Frequency** | Large categories     | Uses counts of occurrences           |
| **Target Encoding**   | Advanced ML          | Uses relationship to target variable |

*

# ordinary encoding

In [39]:
import seaborn as sns 
from sklearn.model_selection import train_test_split
sns.get_dataset_names()
dataset = sns.load_dataset('tips')
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [46]:
print(dataset['day'].value_counts())
print(dataset['time'].value_counts())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [28]:
x = dataset.iloc[:,0:-1]
y = dataset.iloc[:,-1]

In [64]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [65]:
x_train

     total_bill   tip     sex smoker   day    time
99        12.46  1.50    Male     No   Fri  Dinner
25        17.81  2.34    Male     No   Sat  Dinner
211       25.89  5.16    Male    Yes   Sat  Dinner
148        9.78  1.73    Male     No  Thur   Lunch
136       10.33  2.00  Female     No  Thur   Lunch
..          ...   ...     ...    ...   ...     ...
187       30.46  2.00    Male    Yes   Sun  Dinner
166       20.76  2.24    Male     No   Sun  Dinner
47        32.40  6.00    Male     No   Sun  Dinner
63        18.29  3.76    Male    Yes   Sat  Dinner
88        24.71  5.85    Male     No  Thur   Lunch

[195 rows x 6 columns]

In [72]:
from sklearn.preprocessing import OrdinalEncoder
col = ['day','time']
oe = OrdinalEncoder(categories = [['Thur','Fri','Sat','Sun'],['Lunch','Dinner']]) 
# categories parameter is used for arrange the order as you wish
oe.fit_transform(x_train[col])

array([[1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [1., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [3., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [1., 0.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [1., 1.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [1., 0.],
       [3., 1.],
       [2., 1.],
       [2., 1.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [2., 1.],
       [1., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [0., 0.]])

In [74]:
# some attributes 
oe.categories_ # shoing the categories name

[array(['Thur', 'Fri', 'Sat', 'Sun'], dtype=object),
 array(['Lunch', 'Dinner'], dtype=object)]

# label Encoding

In [1]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

li = ['Red','Blue','Green','Red']
encoding = le.fit_transform(li)
print(encoding)
print(li)

[2 0 1 2]
['Red', 'Blue', 'Green', 'Red']

In [5]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd 
ds = pd.DataFrame({
           'name': ['yash','rani didi','tanisha','suraj','roshni'],
            'gender': ['M','F','F','M','F'],
          'passed': ['yes','yes','no','yes','no']
})
le = LabelEncoder()
ds_label = ds.copy()

ds_label['Gender_endcoded'] = le.fit_transform(ds_label['gender'])
ds_label['Passed_endcoded'] = le.fit_transform(ds_label['passed'])
print(ds_label)

             name gender passed  Gender_endcoded  Passed_endcoded
0            yash      M    yes                1                1
1            rani      F    yes                0                1
2  rani kamlapati      F     no                0                0
3           suraj      M    yes                1                1
4          roshni      F     no                0                0

# one hot coding
 * pd.get_dummies() is a pandas function used to perform One-Hot Encoding automatically.

In [7]:
# one hot coding
import pandas as pd 
df = pd.DataFrame({
                'colours':  ['Red','Blue','Green','Red']
})
encodeing = pd.get_dummies(df,columns=['colours'] )  #,dtype=int
print(encodeing)

   colours_Blue  colours_Green  colours_Red
0         False          False         True
1          True          False        False
2         False           True        False
3         False          False         True

# practice for encoding

In [3]:
import seaborn as sns 
ds = sns.load_dataset('flights')
ds

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# print(this is alll text )
result = le.fit_transform(ds['month'])
print(ds['month'].value_counts().sum())
print(result)

144
[ 4  3  7  0  8  6  5  1 11 10  9  2  4  3  7  0  8  6  5  1 11 10  9  2
  4  3  7  0  8  6  5  1 11 10  9  2  4  3  7  0  8  6  5  1 11 10  9  2
  4  3  7  0  8  6  5  1 11 10  9  2  4  3  7  0  8  6  5  1 11 10  9  2
  4  3  7  0  8  6  5  1 11 10  9  2  4  3  7  0  8  6  5  1 11 10  9  2
  4  3  7  0  8  6  5  1 11 10  9  2  4  3  7  0  8  6  5  1 11 10  9  2
  4  3  7  0  8  6  5  1 11 10  9  2  4  3  7  0  8  6  5  1 11 10  9  2]

In [7]:
import pandas as pd
encoding = pd.get_dummies(ds['year'])