In [2]:
import numpy as np 
import scipy.stats as stats
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [5]:
ds = sns.load_dataset('titanic')
ds

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [9]:
df = ds[['survived','age','fare']]
df

     survived   age     fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [10]:
df.isnull().sum()

survived      0
age         177
fare          0
dtype: int64

In [12]:
df['age'] = df['age'].fillna(df['age']).mean()

/var/folders/gd/yqc_8r1d50d5ldy5vyd_5lvm0000gn/T/ipykernel_41768/2444480867.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].fillna(df['age']).mean()

In [14]:
df.isnull().sum()

survived    0
age         0
fare        0
dtype: int64

In [18]:
x = df.iloc[:,1:3]
x
y = df.iloc[:,-1]
y

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: fare, Length: 891, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split
x_train ,x_test ,y_train,y_test  = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
x_train

           age      fare
331  29.699118   28.5000
733  29.699118   13.0000
382  29.699118    7.9250
704  29.699118    7.8542
813  29.699118   31.2750
..         ...       ...
106  29.699118    7.6500
270  29.699118   31.0000
860  29.699118   14.1083
435  29.699118  120.0000
102  29.699118   77.2875

[712 rows x 2 columns]